name: React Professional CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Lint Check
      run: npm run lint

    - name: Check for Build Errors
      run: npm run build

    # التصحيح هنا: استخدام lighthouse-ci-action
    - name: Lighthouse Check
      uses: treosh/lighthouse-ci-action@v12
      with:
        temporaryPublicStorage: true # عشان يرفع لك التقرير على رابط مؤقت تشوفه
        uploadArtifacts: true